# Generated by Django 5.1 on 2024-10-07 09:12

import teacher_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_license",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=teacher_app.models.TeacherImagePath("license"),
                    ),
                ),
                ("teacher_description", models.TextField(blank=True, null=True)),
                ("tution_fee", models.IntegerField(default=0)),
                (
                    "tution_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=teacher_app.models.TeacherImagePath("tutionImages"),
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_available_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
