# Generated by Django 5.1 on 2024-10-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
