# Generated by Django 5.1 on 2024-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths_app", "0002_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
